name: nimbrung_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  go_router: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/source-sans-pro/SourceSansPro-Regular.ttf
          style: italic
        - asset: assets/fonts/source-sans-pro/SourceSansPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/source-sans-pro/SourceSansPro-BoldItalic.ttf
          weight: 700
          style: italic
